---
- name: run and show arp
  hosts: cisco-routers
  gather_facts: false
  tasks:
  - name: show arp
    raw: show arp
    register: result_arp

  - name: debug arp
    debug: var=result_arp.stdout_lines

